# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
print("A 3x3x3 array with random values is:")
print(np.random.rand(3,3,3))

A 3x3x3 array with random values is:
[[[0.38906186 0.78750987 0.09483442]
  [0.32179836 0.83316704 0.46188814]
  [0.04799917 0.27304245 0.40311701]]

 [[0.35872395 0.40908588 0.18938735]
  [0.28614716 0.31261643 0.30474857]
  [0.14558308 0.95856599 0.60624622]]

 [[0.56247237 0.78658323 0.97789436]
  [0.66604328 0.11174066 0.2572563 ]
  [0.5724178  0.83857587 0.07947192]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
print("A 5x5 matrix with values 1,2,3,4 just below the diagonal is :")
print(np.diag([1,2,3,4],k=-1))

A 5x5 matrix with values 1,2,3,4 just below the diagonal is :
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
print("A 8x8 matrix filled with Checkerboard pattern is:")
x = np.zeros((8, 8), dtype = int) 
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

A 8x8 matrix filled with Checkerboard pattern is:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
print("A Normalized 5x5 random matrix is:")
x = np.random.rand(5,5)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

A Normalized 5x5 random matrix is:
[[0.         0.3339474  0.25398568 0.51645119 0.61235637]
 [0.42241648 0.07842247 0.7857372  0.26299126 0.7931502 ]
 [0.18587964 0.11963605 0.88678583 0.22132285 0.91583358]
 [0.53764552 0.83675264 0.13978755 0.7423919  0.39860973]
 [0.95568711 0.85370934 1.         0.5724044  0.47078879]]


# 5.  How to find common values between two arrays?

In [5]:
array1 = np.array([10, 20, 30, 40, 50])
print("Array1: ",array1)
array2 = [10, 30, 0]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [10 20 30 40 50]
Array2:  [10, 30, 0]
Common values between two arrays:
[10 30]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
from datetime import datetime, timedelta 
today = datetime.now() # or presentday = datetime.today() 
# Get Yesterday 
yesterday = today - timedelta(1) 
# Get Tomorrow 
tomorrow = today + timedelta(1) 
# strftime() is to format date according to 
# the need by converting them to string 
print("Yesterday = ", yesterday.strftime('%d-%m-%Y')) 
print("Today = ", today.strftime('%d-%m-%Y')) 
print("Tomorrow = ", tomorrow.strftime('%d-%m-%Y')) 

Yesterday =  11-08-2020
Today =  12-08-2020
Tomorrow =  13-08-2020


# 7. Consider two random array A and B, check if they are equal

In [7]:
# 1st WAY of COMPARING TWO ARRAY
A = np.random.rand(3)
B = np.random.rand(3)
print("Array A = ",A)
print("Array B = ",B)
if np.array_equal(A,B):
    print("Array A and B are Equal")
else:
    print("Array A and B are not Equal")

Array A =  [0.61063295 0.41892682 0.38597099]
Array B =  [0.770459   0.32630218 0.9165318 ]
Array A and B are not Equal


In [8]:
# 2nd WAY of COMPARING TWO ARRAY
h=np.array([1,2,3])
i=np.array([1,2,3])
# comparison = h == i
# equal_arrays = comparison.all()#compare two arrays and returns boolean expression
print("Output is True if two arrays are equal")
print("Output is False if two arrays are equal")
# print("Output:",equal_arrays)
print("Output:",(h == i).all())

Output is True if two arrays are equal
Output is False if two arrays are equal
Output: True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
vec=np.random.randn(10,1)#creates a random vector of given order
print("The random vector is-")
print(vec)
max_val=np.amax(vec)#computes the maximum value from a given vector
print("The maximum value in the vector is-")
print(max_val)
loc=np.where(vec==max_val)#find the index of the maximum value
vec[loc]=0
print("The new vector is-")
print(vec)

The random vector is-
[[-0.38139003]
 [-0.56763499]
 [ 0.02612381]
 [-0.335646  ]
 [-0.3053251 ]
 [-0.45867102]
 [ 2.12680429]
 [-0.34438815]
 [-1.89331262]
 [-1.54370288]]
The maximum value in the vector is-
2.126804286007788
The new vector is-
[[-0.38139003]
 [-0.56763499]
 [ 0.02612381]
 [-0.335646  ]
 [-0.3053251 ]
 [-0.45867102]
 [ 0.        ]
 [-0.34438815]
 [-1.89331262]
 [-1.54370288]]


# 9. How to print all the values of an array?

In [10]:
A = np.random.randn(3,)  # creates a random array of given order
print("The array is:")
print(A)
for i in range(len(A)):
    print("The element at index(", i, ") is:", A[i])

The array is:
[-0.38635464 -0.37045542  0.80717492]
The element at index( 0 ) is: -0.3863546371205378
The element at index( 1 ) is: -0.3704554171440534
The element at index( 2 ) is: 0.8071749169651216


In [11]:
A = np.random.randn(3, 3)  # creates a random array of given order
print("The array is:")
print(A)
print(A.size)
for i in range(len(A)):
    for j in range(len(A)):
        print("The element at index(", i, ",", j, ") is:", A[i][j])

The array is:
[[-0.73726751  1.41836333  0.84687812]
 [ 0.85722126 -0.02554429 -0.68455636]
 [ 0.30829095  0.34863673 -3.58755383]]
9
The element at index( 0 , 0 ) is: -0.7372675087562416
The element at index( 0 , 1 ) is: 1.4183633259855952
The element at index( 0 , 2 ) is: 0.8468781160624859
The element at index( 1 , 0 ) is: 0.8572212646418327
The element at index( 1 , 1 ) is: -0.025544286716531046
The element at index( 1 , 2 ) is: -0.6845563564323912
The element at index( 2 , 0 ) is: 0.3082909512640648
The element at index( 2 , 1 ) is: 0.34863673320532373
The element at index( 2 , 2 ) is: -3.5875538322814156


# 10.Subtract the mean of each row of a matrix

In [12]:
arr = np.random.randn(3, 3)  #creates a random matrix of given order
print("The matrix is-")
print(arr)
print("The mean value of each row is- ")
arr1 = np.mean(arr, axis=1)  #computes the mean of each row
print(arr1)
arr2 = arr - arr1.T
print("The matrix after the mean is subtracted-")
print(arr2)

The matrix is-
[[-0.34476209 -0.77187857 -1.75823901]
 [ 1.20782599  0.29834321 -1.03784422]
 [ 0.41528372 -0.32953183  0.30622553]]
The mean value of each row is- 
[-0.95829323  0.15610833  0.13065914]
The matrix after the mean is subtracted-
[[ 0.61353113 -0.9279869  -1.88889815]
 [ 2.16611921  0.14223488 -1.16850336]
 [ 1.37357695 -0.48564016  0.17556639]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [13]:
Z = np.ones(10)
print("The original vector is:")
print(Z)
I = np.random.randint(0,len(Z),20)
print("The Index values are:")
print(I)
Z += np.bincount(I, minlength=len(Z))
print("Final vector after adding 1 to corresponding elements at the specified indices:")
print(Z)

The original vector is:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The Index values are:
[8 8 3 2 2 3 6 4 1 7 3 2 9 1 6 1 3 7 2 1]
Final vector after adding 1 to corresponding elements at the specified indices:
[1. 5. 5. 5. 2. 1. 3. 3. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [14]:
A = np.random.randn(3, 3)  #creates a random matrix of given order
print("The first 3X3 array is- ")
print(A,"\n")
B = np.random.randn(3, 3)  #creates a random matrix of given order
print("The second 3X3 array is- ")
print(B,"\n")
C = np.dot(A, B)  #computes the dot product of two given matrices
print("The corresponding dot product is- ")
print(C,"\n")
DIAG = np.diag(C)  #choose the diagnol elements of given matrix
print("The corresponding diagnol elements are- ")
print(DIAG,"\n")

The first 3X3 array is- 
[[ 0.75503157 -0.73948328  0.30588481]
 [-0.98707707 -0.22811415  1.35029956]
 [-0.84277032  0.63807587 -0.16246526]] 

The second 3X3 array is- 
[[-0.430032    0.24062906  1.60170175]
 [ 0.39301238 -0.3300358  -0.48146851]
 [ 0.30360783  0.95370732 -0.1682924 ]] 

The corresponding dot product is- 
[[-0.5224448   0.71746307  1.5138952 ]
 [ 0.74478456  1.12555699 -1.69841845]
 [ 0.5638642  -0.56832721 -1.62973846]] 

The corresponding diagnol elements are- 
[-0.5224448   1.12555699 -1.62973846] 



# 13.How to find the most frequent value in an array?

In [15]:
k = np.array(
    [1, 2, 3, 1, 2, 3, 2, 2, 4, 5, 6, 7, 8, 9])
np.argmax(np.bincount(k))  #finds the value that is repeated maximum number of times in a given array

2

# 14.How to get the n largest values of an array

In [16]:
A=np.arange(1000)#generates a sequential array with numbers 0 to 999
np.random.shuffle(A)
n=int(input("Enter the value of n:"))
print("The",n,"largest value of the array are:")
print (A[np.argpartition(-A,n)[:n]])#prints the n largest values in the specified array

Enter the value of n:2
The 2 largest value of the array are:
[999 998]


In [17]:
A = np.arange(1000)  #generates a sequential array with numbers 0 to 999
np.random.shuffle(A)
n = int(input("Enter the value of n:"))
print("The", n, "largest value of the array are:")
print(A[np.argsort(A)[-n:]])  #prints the n largest values in the specified array

Enter the value of n:2
The 2 largest value of the array are:
[998 999]


# 15.How to create a record array from a regular array?

In [18]:
arr = np.array([["Nikhil Agarwal", 88.5, 90],["Dhananjay Verma", 87, 99],["B S Puneeth", 85.5, 91]])#generates a 2D array
print("Original array is:\n")
print(arr)
print("Record array is:\n")
rec_arr = np.core.records.fromarrays(arr.T,names='col1, col2, col3',formats = 'S80, f8, i8')# generates a reccord array
print(arr)
type(rec_arr)

Original array is:

[['Nikhil Agarwal' '88.5' '90']
 ['Dhananjay Verma' '87' '99']
 ['B S Puneeth' '85.5' '91']]
Record array is:

[['Nikhil Agarwal' '88.5' '90']
 ['Dhananjay Verma' '87' '99']
 ['B S Puneeth' '85.5' '91']]


numpy.recarray